version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
     - ./redis/redis.conf:/redis.conf
     - ./redis:/data
    restart: always
    env_file:
      - redis/.env
    container_name: redis
    command: ["redis-server", "/redis.conf"]
    networks:
      - sp

  quart_sp:
    container_name: quart_sp
    env_file:
      - quart_sp/.env
    restart: always
    build:
      context: quart_sp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - 5000
    command: hypercorn -w 1 -b 0.0.0.0:5000 asgi:app
    networks:
      - sp

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - quart_sp
    networks:
      - sp

networks:
  sp:
    driver: bridge