version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
     - ./redis/redis.conf:/redis.conf
     - ./redis:/data
    restart: always
    env_file:
      - redis/.env
    container_name: redis
    command: ["redis-server", "/redis.conf"]

  flask_spotify:
    container_name: flask_spotify
    env_file:
      - flask_spotify/.env
    restart: always
    build: ./flask_spotify
    ports:
      - "5000:5000"
    command: bash -c "gunicorn --worker-class eventlet -w 1  -b 0.0.0.0:5000 wsgi:app
              && gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 module:app"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_spotify
