version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
     - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    container_name: redis

  flask_spotify:
    container_name: flask_spotify
    env_file:
      - flask_spotify/.env
    restart: always
    build: ./flask_spotify
    ports:
      - "8000:8000"
    command: gunicorn -w 3 --threads 2 -b 0.0.0.0:8000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_spotify
