version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
     - ./config/redis.conf:/redis.conf
    restart: always
    env_file:
      - config/.env
    container_name: redis
    command: ["redis-server", "/redis.conf"]

  flask_spotify:
    container_name: flask_spotify
    env_file:
      - flask_spotify/.env
    restart: always
    build: ./flask_spotify
    ports:
      - "5000:5000"
    command: gunicorn -w 3 --threads 2 -b 0.0.0.0:5000 wsgi:app
    network_mode: "host"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_spotify
